### PR TITLE
add green tick for each successful program name

### PR DESCRIPTION
**Pull request by abazlinton**
Addresses #32 

One line per app, so should be succinct enough @craig

image

### CODE REVIEW

**Comment by JarrodBennie** [comment]
It would look a lot nicer if the emoji was first, then the text.

**Comment by abazlinton** [comment]
@JarrodBennie happy now! :P

**Comment by JarrodBennie** [comment]
Ecstatic, Alex.

**Comment by craig** [comment]
>One line per app, so should be succinct enough @craig

No, not good enough.

**Pull request merged**
