### PR TITLE
Remove Sublime Text

### PR DESCRIPTION
**Pull request by ajrussellaudio**
Let us not be sad that it is over. Let us be glad for the time we had together.

* Removes line from script which installs Sublime Text
* Removes all the Sublime configuration
* Sets Atom as the default editor
* Updates the README with more links and formatting to match other CodeClan repos

### CODE REVIEW

**Comment by ajrussellaudio** [comment]
Added flags so that Atom works for e.g. `git merge` messages

**Comment by matthew-healy** [comment]
Any plans to use `apm` (which ships with Atom) to install some similar packages to the ones we had for Sublime? Also hi.

**Comment by ajrussellaudio** [comment]
Hi! I think Atom comes with everything we need to get started out of the box. 

For things like unusual syntax highlighting, I think it's better to make the package install part of the lesson, rather than include it for free. It was a good moment when, in React week, students all realise at the same time that Sublime didn't handle JSX highlighting properly, and then we can point them at Package Control. It would be good if moments like that could be replicated in Atom

**Comment by matthew-healy** [comment]
Fair. 👍

**Comment by ajrussellaudio** [comment]
I've tested this on a clean laptop today, and it definitely doesn't install Sublime Text. 100% Sublime free. Atom works as the default editor for Git.

So I'm going to go ahead and merge my own PR, because I'm a maverick who don't play by nobody's rules but my own.

**Pull request merged**
